name: Mobilewright Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm install

      - name: Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          arch: x86_64
          profile: Nexus 6
          emulator-boot-timeout: 1200
          script: |
            adb devices

            adb wait-for-device

            until adb shell getprop sys.boot_completed | grep -m 1 "1"; do
              echo "Waiting for emulator..."
              adb devices
              sleep 10
            done

            echo "Emulator booted"

            adb devices

            npx mobilewright test