name: Mobilewright Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm install

      - name: Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          profile: pixel_6
          script: |
            adb devices
            npx mobilewright test